### ISSUE TITLE
perfectPixel

### ISSUE THREAD

**Issue by alextsk** [alexanderkif/resume#1]
привет. выложи, пожалуйста, скриншот с открытыми наcтройками PerfectPixel с инверсией

**Comment by alexanderkif** [comment]
привет. в корне PerfectPixelScreen.png

**Comment by alextsk** [comment]
там только кусок страницы, выложи всю, можно прямо сюда в ишью, они перетаскиванием вставляются, в проекте это, наверное, лишнее. и поставь прозрачность примерно на половину

**Comment by alexanderkif** [comment]
не могу найти, как сохранить всю страницу. не в паинте же склеивать ) подскажите плз

**Comment by alextsk** [comment]
есть куча расширений для браузера, я пользуюсь Awesome Screenshot: Screen Video Recorder.
и может лучше на 'ты'? я тут один)

**Comment by alexanderkif** [comment]
![image](https://user-images.githubusercontent.com/19386299/47784636-9c408980-dd1f-11e8-87a7-429ec30ca985.png)

**Comment by alexanderkif** [comment]
Awesome Screenshot оказалось тоже склеивает части скриншота, причем с пропусками. Или что-то не так делаю. Я жму ctrl+shift+e. Вообщем я сам в паинте лучше склеиваю. 
![image](https://user-images.githubusercontent.com/19386299/47786962-e24d1b80-dd26-11e8-81f9-9e226b2c4c67.png)

**Comment by alexanderkif** [comment]
А иконки я из материал взял, по согласованию с Сергеем

**Comment by alextsk** [comment]
тогда все ок
