### ISSUE TITLE
Адаптив

### ISSUE THREAD

**Issue by prodderman** [alexanderkif/resume#11]
https://github.com/alexanderkif/flatUI/issues/15

**Comment by GoodDayTodayOkey** [comment]
Сделать перестройку макета в одну колонку при ширине экрана 600px

**Comment by alexanderkif** [comment]
вьюпорт добавил.
макет перестраивается в одну колонку уже при 850px, а software около 570px.
мне казалось - так лучше... переделать?

**Comment by prodderman** [comment]
Почему width=500? вьпорт должен подстраиваться под ширину девайса

**Comment by alexanderkif** [comment]
сделал
