### ISSUE TITLE
Блок Contact

### ISSUE THREAD

**Issue by prodderman** [alexanderkif/resume#12]
Для телефонов, емейлов и прочих надо использовать `<a>` с адресом. 
Например `<a href="mailto: mail@mail.ru">mail@mail.ru</a>`

**Comment by alexanderkif** [comment]
сделано.

**Comment by prodderman** [comment]
Не понятно зачем ты разделил value на prefix и value. Плюс, ты не используешь префикс отдельно от  значения

**Comment by alexanderkif** [comment]
value используется дважды в href и внутри <a>. а как бы ты сделал?

**Comment by prodderman** [comment]
```
{
    name: 'email',
    displayValue: 'contact@domain.com',
    value: 'mailto:contact@domain.com',
}
```

**Comment by alexanderkif** [comment]
а если контент менеджеру доверят править адреса? у него будет шанс накосячить дважды :)

**Comment by prodderman** [comment]
Твой способ довольно не очевидный, так как можно подумать, что, например, у урлов может быть разный протокол. Во-вторых смешиваются данные и представление. К примеру, телефон может быть задан так: 
```<a href="tel:+777777777">Звонить сюда</a>```
Для данного макета это не критично, но это так, на будущее.

**Comment by alexanderkif** [comment]
сделал
