### ISSUE TITLE
Perfect Pixel

### ISSUE THREAD

**Issue by GoodDayTodayOkey** [alexanderkif/resume#16]
Можешь плиз приложить сюда скрин в инверсии с Pixel Perfect, с параметрами настройки.

**Comment by alexanderkif** [comment]
![image](https://user-images.githubusercontent.com/19386299/53188009-db238380-361d-11e9-97c7-25363bab0bc3.png)

**Comment by GoodDayTodayOkey** [comment]
Ту много расхождений которые следует подправить) Лампочку, для блоков experiece, software, education смещение, место под фотографию

**Comment by GoodDayTodayOkey** [comment]
Как подправишь выложи тут скрин снова плиз

**Comment by alexanderkif** [comment]
![image](https://user-images.githubusercontent.com/19386299/53300659-cb957c00-3863-11e9-94cb-90dfcb34873f.png)
Лампочка заменена по согласованию с Сергеем.
