### ISSUE TITLE
package.json

### ISSUE THREAD

**Issue by GoodDayTodayOkey** [alexanderkif/resume#17]
Разнести нужные пакеты для devDependencies, dependencies.

**Comment by alexanderkif** [comment]
а что надо в dependencies переносить? вроде это все требуется только в разработке.

**Comment by GoodDayTodayOkey** [comment]
devDependencies — пакеты, которые нужны для разработки.

**Comment by GoodDayTodayOkey** [comment]
dependencies — пакеты, от которых ваш пакет зависит непосредственно.

**Comment by GoodDayTodayOkey** [comment]
Компиляторы-транспиляторы-трансляторы (типа Coffee, LESS, Jade), тест-раннеры, стайл-чекеры и линтеры (mocha, chai, karma, (js|es)lint, jscs), плагины для таск-раннеров (grunt-contrib-watch, gulp-jade) — все это обычно ставится как --save-dev, потому что нужно только тем, кто контрибьютит в этот проект, работает с его кодом.

Библиотеки и фреймворки (expressjs, jquery, backbone), на основе которых работает ваш код, без которых ваш код не запустится у его потребителя — ставятся как --save.

**Comment by alexanderkif** [comment]
нет в этом проекте ничего из вышеперечисленного (expressjs, jquery, backbone). Семь раз проверил )))

**Comment by GoodDayTodayOkey** [comment]
Зато есть webpack)

**Comment by GoodDayTodayOkey** [comment]
Обсудили эту тему, в общем в dependencies  должны быть webpack и loaderы которые используешь для создания production сборки, в все что необходимо для разработки development  webpack-dev-server, webpack-dev-server, webpack-cli, gh-pages в твоем случае

**Comment by GoodDayTodayOkey** [comment]
Как исправишь можешь закрывать ишью
