### ISSUE TITLE
px

### ISSUE THREAD

**Issue by GoodDayTodayOkey** [alexanderkif/resume#18]
Перевести в rem, объяснить тут почему не стоит использовать px.

**Comment by alexanderkif** [comment]
> после всех исследований я пришел к выводу, что единственным преимуществом rem является то, что пользователи, которые используют размер шрифта большего размера в настройках браузера, получат размер шрифта, масштабированный правильно, а px не будет масштабироваться
> большинство пользователей используют масштабирование вместо изменения размера шрифта в своем браузере и телефонах

**Comment by GoodDayTodayOkey** [comment]
Ответ верный но не совсем полный, если тебе придется адаптировать сайт под медиа запросы, достаточно удобно использовать rem (изменив размер только в одном месте), и править только те блоки которые были неудачно c маштабированы, ктому же легко вычислить текущее значение. С px придется перелопатить весь проект.  Использование em тоже может принести не мало хлопот. https://learn.javascript.ru/css-units вот источник полезный к прочтению. Ишью можешь закрывать.

**Comment by alexanderkif** [comment]
спасибо. fixed
