### ISSUE TITLE
margin

### ISSUE THREAD

**Issue by GoodDayTodayOkey** [alexanderkif/resume#19]
Убрать margin у блоков объяснить тут почему этого не стоит их использовать, пути обхода.

**Comment by alexanderkif** [comment]
нельзя использовать маржины, чтобы блок не влиял на родителя. при необходимости использовать паддинг у родителя.

**Comment by GoodDayTodayOkey** [comment]
Почему у родителя? Что произойдет если ты будешь переиспользовать родителя с другим дочерним блоком, к примеру на другой странице. Почему не инкапсулировать отступы внутри блока применяя их к элементам блока?

**Comment by GoodDayTodayOkey** [comment]
Удалить padding-top, на body допускается использовать только padding 0, margin 0 - чтобы убрать отступы. Удалить у body display flex и justify-content, что будет если на другой странице тебе не нужен будет display flex?

**Comment by alexanderkif** [comment]
а можно использовать в блоке `margin: 0 auto;` ? в cv?

**Comment by GoodDayTodayOkey** [comment]
На блоке не должно висеть внешнее позиционирование.

**Comment by alexanderkif** [comment]
сейчас так:
`body {
    text-align: -webkit-center;
}`
в cv маржинов нет.

**Comment by GoodDayTodayOkey** [comment]
@media screen and (max-width: 52.9rem) {
        justify-content: center;
        margin: 0;
    }

**Comment by GoodDayTodayOkey** [comment]
Как исправишь можешь закрывать ишью
