### ISSUE TITLE
.profile__text-b реализовать через модификатор

### ISSUE THREAD

**Issue by GoodDayTodayOkey** [alexanderkif/resume#24]

**Comment by alexanderkif** [comment]
сделано

**Comment by GoodDayTodayOkey** [comment]
Это не верное именование. Почитай в бэме про типы модификаторов и переименуй)

**Comment by alexanderkif** [comment]
так верно?

**Comment by GoodDayTodayOkey** [comment]
bold это булевый модификатор?

**Comment by alexanderkif** [comment]
так верно?

**Comment by GoodDayTodayOkey** [comment]
Используй вместо font-weight_bold - display_bold, это будет иметь более широкие возможности  его применения, к примеру если захочется текст сделать курсивом.

**Comment by GoodDayTodayOkey** [comment]
Как сделаешь можешь закрывать ишью.
