### ISSUE TITLE
main.scss

### ISSUE THREAD

**Issue by GoodDayTodayOkey** [alexanderkif/resume#25]
Реализовать автоматический импорт стилей

**Comment by alexanderkif** [comment]
сделано

**Comment by GoodDayTodayOkey** [comment]
![Снимок экрана от 2019-04-05 16-58-17](https://user-images.githubusercontent.com/31854808/55620089-3d96a480-57c4-11e9-9325-ef7ff7b9574a.png)
Я имел ввиду автоматически подключать все стили в index.js.

**Comment by GoodDayTodayOkey** [comment]
https://www.npmjs.com/package/require-context

**Comment by alexanderkif** [comment]
это из flatUI содержимое. тут такое:
```
import './scss/main.scss';
import './img/favicon.ico';
```
может тут и не имеет смысла?

**Comment by alexanderkif** [comment]
вот эти импорты в scss файле. а как быть с переменными из этого же файла?
```
$base-color: #056cb4;
$bg-color: white;
```
и как материал импортировать из другого места?
`@import '~material-icons/iconfont/material-icons.scss';`
и сомневаюсь, что улучшится читаемость кода от этого.

**Comment by GoodDayTodayOkey** [comment]
Про стороние либы я уже писал про npm пакеты, с константами их нужно вынести в файл constans и его также автоматически импортить. Читаемость кода повысится из за того что будет отсуствовать портянка с импортами и нет необходимости проверять все ли заимпорчено.

**Comment by alexanderkif** [comment]
сделал, но sass-переменные через js не передаются. и все неочевидно стало, имхо

**Comment by GoodDayTodayOkey** [comment]
Вынеси константы в отдельный файл constants и импорть его руками в файлы где они используются. Как сделаешь можешь закрывать ишью.
