### ISSUE TITLE
config

### ISSUE THREAD

**Issue by GoodDayTodayOkey** [alexanderkif/resume#28]
Для чего ты исключаешь из сборки main.js, а потом его руками подключаешь в  pug?

**Comment by alexanderkif** [comment]
не могу найти, как подключить  по другому. подскажешь?

**Comment by GoodDayTodayOkey** [comment]
Убрать из конфига HtmlWebpackPlugin правило inject: false, и удалить скрипт из pug.

**Comment by alexanderkif** [comment]
спасибо. а то я вчера столько всего бесполезного перечитал...
