### ISSUE TITLE
Padding

### ISSUE THREAD

**Issue by GoodDayTodayOkey** [alexanderkif/resume#29]
Не использовать паддинги для позиционирования внутри блока.

**Comment by alexanderkif** [comment]
маржины вроде нельзя. и паддинги тоже нельзя?

**Comment by GoodDayTodayOkey** [comment]
Не во всех кейсах, к примеру если у блока есть рамка, и тебе нужно все элементы спозиционировать относительно этой рамки, в твоих случаях ты используешь паддинги и здесь это заходит. Если же использовать паддинги для внутреннего позиционирования, которое по сути используется исключительно ради внешнего позиционирования содержимого блока относительно других блоков то такой кейс не подходит.

**Comment by alexanderkif** [comment]
проверь пожалуйста, правильно ли я понял

**Comment by GoodDayTodayOkey** [comment]
Все верно, только в header остались padding-left, right

**Comment by alexanderkif** [comment]
убрал
