### ISSUE TITLE
gh-pages

### ISSUE THREAD

**Issue by alextsk** [alexanderkif/resume#3]
с отдельной веткой стало лучше, теперь надо избавиться от сборки в ветках разработки.
т.е. от папки dist в данном случае. 
и в gh-pages сами исходники тоже не нужны.
можно это делать руками через orpfan ветки, но проще через плагин для вебпака, есть скрипт gh-pages в npm, вариантов масса, эта задача не редкость

**Comment by alexanderkif** [comment]
подключил gh-pages. теперь без dist/

**Comment by alextsk** [comment]
я пока вижу папку dist. ты ее возможно в гитигнор забыл добавить

**Comment by alexanderkif** [comment]
dist удалил, в гитигнор добавил. только коммиты подписал #2 :(
