### ISSUE TITLE
блок Contact

### ISSUE THREAD

**Issue by GoodDayTodayOkey** [alexanderkif/resume#30]
1) Ссылки на чужие сайты должны содержать атрибут target="_blank", чтобы открываться в новом окне;
2) Все ссылки с target="_blank" должны так же содержать атрибут rel="noopener noreferrer";
3) Для телефонов и mail  https://rizzoma.com/topic/a87a0a28b84d6326d4f3909e8801dab7/0_b_8nel_78ibe/

**Comment by alexanderkif** [comment]
сделано
