### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by alextsk** [alexanderkif/resume#4]
сайт должен адаптироваться под разные разрешения, 
https://rizzoma.com/topic/d5c429337bcaa70548fb5aeedee6d92b/0_b_8ndo_7avvn/
тут макет простой должно хватить одной точки перехода( но можно и больше), при ширине 480px горизонтальной прокрутки точно быть не должно

**Comment by alexanderkif** [comment]
добавил. не знаю, правильно или нет.

**Comment by alextsk** [comment]
норм, software тоже есть смысл по одному элементу расположить

**Comment by alexanderkif** [comment]
привет. сделал. меньше 600px - вертикально
