### ISSUE TITLE
Data

### ISSUE THREAD

**Issue by alextsk** [alexanderkif/resume#6]
сейчас данные хранятся в паг файле, это не очень реалистично, лучше вынести их в отдельный json файл и импортировать его.

при передаче параметров в миксинах нужно использовать деструктуризацию по максимуму, 
индексированным параметрам лучше дать имена, например
.contact__name= cont[0]
cont[0] должно быть просто cont.name 

вообще посмотри на имена параметров, например highlighted=="highlighted" звучит странно, тут либо highlighted==true, либо theme=='highlighted' 

software.leftList - схема данных не должна знать о представлении, однородные данные одним списком

**Comment by alextsk** [comment]
JSON.parse(fs.readFileSync - почему так? вебпак же умеет json импортировать
```
 - for (var x = 0; x < software.softList.length; x++)
                if x < software.softList.length/2
```
не проще их выводить в одном контейнере и колонки стилями задавать?

деструктуризации пока нет, это вот так например:
> mixin contact({icon, header})
>  ....
>             +header(icon, header)

**Comment by alexanderkif** [comment]
привет. а сейчас импорт json правильно? software сделал через grid, по media оставляю одну колонку. Деструктуризацию вроде сделал, только в комменте к коммиту декомпозицию наспех написал )

**Comment by alextsk** [comment]
привет. да, импорт норм. он и раньше работал, просто зачем обращаться напрямую к файловой системе если вебпак уже используется. вроде тут все ок, закрываю
