### ISSUE TITLE
HTML 

### ISSUE THREAD

**Issue by alextsk** [alexanderkif/resume#7]
хтмл предполагает использование осмысленных тегов, ul для списков, параграфы для текста, и т.д. 
сейчас используются только div

**Comment by alexanderkif** [comment]
привет. тексты сделал параграфами, списки - списками.

**Comment by alexanderkif** [comment]
почитал. добавил.

**Comment by alextsk** [comment]
education и experience все же списки, я имел ввиду в них нужен контейнер для unit, и вот контейнер будет уже li
unit - все так же задает внешнее позиционирование даже если маржин на внутреннем элементе, эту проблему тоже решит контейнер

**Comment by alexanderkif** [comment]
переделал. насчет маржинов у юнита не понял

**Comment by alextsk** [comment]
вот это границы элемента
![1](https://user-images.githubusercontent.com/16453186/48316464-9186ce00-e616-11e8-8da3-c3173a61f616.png)
а вот это маржин
![2](https://user-images.githubusercontent.com/16453186/48316465-93e92800-e616-11e8-8ed3-736bde241c8e.png)
т.е. по прежнему блок отвечает за свое позиционирование относительно соседей
подробнее можно погуглить margin-collapse 

кстати, посмотри почему правило два раза импортируется

**Comment by alexanderkif** [comment]
маржин убрал. импорт стилей юнита был и в двух местах, перенес в main.scss

**Comment by alextsk** [comment]
li нужно дать имена по бэм
