### ISSUE TITLE
Decorations

### ISSUE THREAD

**Issue by alextsk** [alexanderkif/resume#8]
часто нет необходимости для декорации вводить дополнительные элементы и обвешивать их классами, с этим справляются псевдоэлементы before и after. как минимум большой круг можно сделать простым html элементом, т.к. предполагается что туда будет вставляться фото. линии в заголовках и обводку на иконках тоже можно сделать проще. посмотри, может еще что нибудь заметишь.

**Comment by alexanderkif** [comment]
привет. большой круг и иконки сделал с before. насчет линий в заголовках не получилось менять их длину, если через text-decoration делать.
